################################# Default configuration ###################
# provide your domain here
baseURL = "http://localhost:7171"
relativeURLs = true
# theme
# theme = "x"

# site title
title = "Amy ERP/CRM"
# disable language
disableLanguages = []
# Default language
DefaultContentLanguage = "en"

[params]
foo='bar'

# unsafe html
[markup.goldmark.renderer]
unsafe = true

#
